on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
     matrix:
        include:
          - container: ghcr.io/seanavery/viam-cpp-base:0.0.2
            TARGET: jetson
            META_PATH: meta.json
          - container: ghcr.io/seanavery/viam-cpp-base-pi:0.0.2
            TARGET: pi
            META_PATH: meta-pi.json
    container:
      image: ${{ matrix.container }}
      options: --platform linux/arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "TARGET=${{ matrix.TARGET }}" >> $GITHUB_ENV
          echo "META_PATH=${{ matrix.META_PATH }}" >> $GITHUB_ENV

      - name: Clean build artifacts
        run: make clean

      - name: Install module dependencies
        run: make dep

      - name: Build viam-csi binary
        run: make build

      - name: Build viam-csi appimage
        run: make package

      - name: Copy binary and appimage to bin folder and archive
        run: make bin && tar czf module.tar.gz ./bin/*.AppImage

      - name: Run appimage in fresh instance
        run: |
          make image-test
          make test-package

      - name: Upload Module
        uses: viamrobotics/upload-module@main
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          meta-path: ${{ env.META_PATH }}
          module-path: bin/viam-csi-latest-aarch64.AppImage
          platform: linux/arm64
          version: ${{ github.ref_name }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
